# Generated by Django 5.1.1 on 2024-09-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('jobs_term', models.CharField(choices=[('long', 'LongTime'), ('onetime', 'OneTime')], max_length=20)),
                ('logistika', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('tajribasiz', 'Tajribasiz'), ('tajribali', 'Tajribali')], max_length=30)),
                ('salary', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('jami ishchilar soni', models.IntegerField()),
                ('jobstype', models.CharField(choices=[('online', 'online'), ('ofline', 'ofline')], max_length=244)),
                ('diplom', models.CharField(choices=[('muhum emas', 'Muhum emas'), ('bakalavir', 'Bakalavir'), ('magistir', 'Magister')], max_length=122)),
            ],
        ),
    ]
