# Generated by Django 5.1.1 on 2024-09-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsadd',
            name='degree',
        ),
    ]
