# Generated by Django 5.1.1 on 2024-09-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('server_salary', models.IntegerField()),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
    ]
