# Generated by Django 5.1.1 on 2024-09-15 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_region'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serveradd',
            name='contact',
        ),
        migrations.AddField(
            model_name='serveradd',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.region'),
            preserve_default=False,
        ),
    ]
